# This file is symlinked in project's git root directory, so regardless of opening the whole project's git root dir or only
# ./android subdir in Android Studio, it will make AS see the same properties, because they are read only from the opened project's root directory,
# and can't be linked or imported from submodules (like app module which is defined as ./android folder in project's git root settings.gradle)
androidApiLevel=36
androidBuildToolsVersion=36.0.0
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false
android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
